apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soccer-learning-artifacts
  namespace: des-soccer-learning
  labels:
    app.kubernetes.io/name: des-soccer-learning
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
